import React, {useEffect} from 'react';
import Head from "next/head";
import styles from '../../styles/Home.module.css'
import {useAppContext} from "../../lib/util/app-context";
import {useRouter} from "next/router";

// todo(turnip): improve layout and extract css
export default function Admin() {
    const {profile} = useAppContext();
    const router = useRouter();

    useEffect(() => {
        if (!profile) {
            void router.push("/admin/login/");
        }
    }, [profile])


    if (!profile) {
        return <></>
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <form className={styles.center} style={{["display"]: "flex", ["flexDirection"]: "column"}}>
                    Admin
                </form>
            </main>
        </>
    );
}
