import React, {useEffect, useRef} from 'react';
import Head from "next/head";
import styles from '../../../styles/Home.module.css'
import {Button, TextField, TextFieldProps} from "@mui/material";
import {useAppContext} from "../../../lib/util/app-context";
import {useRouter} from "next/router";
import {login} from "../../../lib/clients/turnip/api/login";

// todo(turnip): improve layout and extract css
export default function Login() {
    // from Ido @ https://stackoverflow.com/a/63690287/17836168
    const {profile, setProfile, turnipClient, setOptions} = useAppContext();
    const router = useRouter();

    const usernameRef = useRef<TextFieldProps>();
    const passwordRef = useRef<TextFieldProps>();

    useEffect(() => {
        if (profile) {
            void router.push("/admin/");
        }
    }, [profile, router])


    if (profile) {
        return <></>
    }

    const onClickLogin = () => {
        // todo: prevent double clicking using hook!
        login({
            turnipClient: turnipClient!,
            username: usernameRef.current?.value as string,
            password: passwordRef.current?.value as string,
            setProfile: setProfile!,
            setOptions: setOptions!,
        });
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <form className={styles.center} style={{["display"]: "flex", ["flexDirection"]: "column"}}>
                    <TextField name="Username" label="Username" variant="outlined" inputRef={usernameRef}/>
                    <TextField name="Password" label="Password" variant="outlined" inputRef={passwordRef}/>
                    <Button variant="outlined" onClick={onClickLogin}>Login</Button>
                </form>
            </main>
        </>
    );
}
