import useAuthAdminRedirect from "../../../../lib/util/use-auth-admin-redirect";
import React from "react";
import {useAppContext} from "../../../../lib/util/app-context";
import Head from "next/head";
import {Button} from "@mui/material";

export default function ContentNewIndex() {
    const {profile, turnipClient, options, setContentListProp} = useAppContext();

    useAuthAdminRedirect();
    if (!profile) {
        return <></>;
    }

    return (
        <>
            <Head>
                <title>New Content - Admin</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h1>New Content</h1>
                <br/>
                <Button>Save</Button>
            </main>
        </>
    );
}