import {useAppContext} from "../util/app-context";
import React, {useState} from "react";
import {Content} from "turnip_api/ts/rpc/turnip/service";
import useAuthAdminRedirect from "../util/use-auth-admin-redirect";
import Head from "next/head";
import {ContentEdit, ContentEditAction} from "./content-edit";

export interface ContentNewPageProps {
    content?: Content;
}

export const ContentNewPage = (props: ContentNewPageProps) => {
    const {profile} = useAppContext();
    const [content] = useState<Content>((() => {
        if (props.content) {
            return props.content;
        }

        return {
            title: "",
            description: "",
            content: "",
            tagList: [],
            meta: {},
            primaryId: "10000000-0000-0000-0000-e4d1a9ddc777", // todo: make this optional
            authorId: "",
        };
    })());

    useAuthAdminRedirect();
    if (!profile) {
        return <></>;
    }

    return (
        <>
            <Head>
                <title>New Content - Admin</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h1>New Content</h1>
                <br/>
                <br/>
                {ContentEdit({
                    content: content,
                    action: ContentEditAction.Create,
                })}
            </main>
        </>
    );
};