import React, {useEffect, useRef, useState} from 'react';
import {useRouter} from "next/router";
import {useAppContext} from "../../../lib/util/app-context";
import {Content} from "turnip_api/ts/rpc/turnip/service";
import {Button, List, ListItem, TextField, TextFieldProps} from "@mui/material";
import Head from "next/head";
import useEffectOnce from "../../../lib/util/use-effect-once";
import useAuthAdminRedirect from "../../../lib/util/use-auth-admin-redirect";

export default function ContentSlug() {
    const {profile, contentListProp, setContentListProp, turnipClient, options} = useAppContext();
    // todo: refactor
    const [content] = useState<Content>((() => {
        if (contentListProp.length !== 1) {
            return {
                title: "",
                description: "",
                content: "",
                tagList: [],
                meta: {"client_error": "wrong contentListProp set"},
                primaryId: "",
                authorId: "",
            }
        }
        return contentListProp[0];
    })());

    const router = useRouter()
    const titleRef = useRef<TextFieldProps>();
    const contentRef = useRef<TextFieldProps>();
    const descriptionRef = useRef<TextFieldProps>();
    const [tagList, setTagList] = useState<string[]>(content.tagList)

    // re-route if setting the contentList went wrong
    useEffect(() => {
        if (content.meta["client_error"] === "wrong contentListProp set") {
            alert("Something went wrong!");
            void router.push("/admin/contents/");
        }
    }, [content, router])
    // cleanup to avoid data leak
    useEffectOnce(() => {
        setContentListProp!([]); // avoid data leak
    })

    const updateContent = () => {
        // todo: debouncing
        turnipClient!.updateContent({
            item: {
                title: titleRef.current?.value as string,
                description: descriptionRef.current?.value as string,
                content: contentRef.current?.value as string,
                tagList: tagList,
                meta: {}, // todo save meta
                primaryId: content.primaryId,
                authorId: content.authorId,
            }
        }, options)
            .then(() => {
                void router.push("/admin/contents/");
            }).catch(err => {
            console.log(err);
        });
    }

    // for faster design iteration, comment this and then later uncomment
    // tip: add a to//do: comment after redesign at the top so you don't forget!
    useAuthAdminRedirect();
    if (!profile) {
        return <></>
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className={"blockAllChildren"}>

                    <h2>Content: {content.primaryId}</h2>
                    {/*todo: expand text field*/}
                    <TextField name="Title"
                               label="Title"
                               variant="outlined"
                               defaultValue={content.title}
                               style={{marginBottom: "1em"}}
                               inputRef={titleRef}
                    />
                    <TextField
                        name="Content"
                        label="Content"
                        id="outlined-multiline-flexible"
                        multiline
                        maxRows={10}
                        defaultValue={content.content}
                        style={{marginBottom: "1em"}}
                        inputRef={contentRef}
                    />
                    <TextField
                        id="outlined-multiline-flexible"
                        name="Description"
                        label="Description"
                        multiline
                        maxRows={10}
                        defaultValue={content.description}
                        style={{marginBottom: "1em"}}
                        inputRef={descriptionRef}
                    />
                    <h3>Media (TODO)</h3>
                    <h3>Tags</h3>
                    <List>
                        {tagList.map((value, index) => {
                            return (<ListItem key={value}>
                                <Button onClick={() => {
                                    tagList.splice(index);
                                    setTagList([...tagList]);
                                }}>-</Button>
                                <TextField
                                    defaultValue={value}
                                    onChange={(newValue) => {
                                        tagList[index] = newValue.target.value;
                                    }}></TextField>
                            </ListItem>);
                        })}
                        <ListItem><Button onClick={() => {
                            tagList.push("new tag");
                            setTagList([...tagList]);
                        }}>+</Button> Create new tag</ListItem>
                    </List>
                    <br/>
                    <h3>Access Details (TODO)</h3>
                    <Button variant="outlined" onClick={updateContent}>Save</Button>
                </div>

            </main>
        </>
    );
}
